# Generated by Django 6.0.3 on 2026-03-23 00:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Título')),
                ('description', models.TextField(verbose_name='Descrição')),
                ('duration', models.IntegerField(help_text='Duração em minutos', verbose_name='Duração')),
                ('release_date', models.DateField(verbose_name='Data de Lançamento')),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room', models.CharField(max_length=50, verbose_name='Sala')),
                ('start_time', models.DateTimeField(verbose_name='Horário de Início')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Preço do Ingresso')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='movies.movie')),
            ],
        ),
    ]
